version: '3'
services: 
  redis-server:
    image: 'redis'
  mongo-server:
    image: 'mongo'
  node-server:
    restart: on-failure
    build: .
    ports: 
      - "4000:4000"

# docker-compose up --build to build and run